### ISSUE TITLE
编译的内核版本

### ISSUE THREAD

**Issue by xiangyu123** [jlijian3/lvs-snat#2]
请问一下，你是在具体哪个内核的版本上编译成功的。精确到操作系统版本和内核的小版本。我一直尝试，但是一直没有成功

**Comment by jlijian3** [comment]
阿里内核
https://github.com/alibaba/LVS

**Comment by xiangyu123** [comment]
好的，多谢。

**Comment by xiangyu123** [comment]
我是在centos6.7上编译的。 编译通过，但是启动后看不到网卡。请问你遇到过类似的问题么？

**Comment by jlijian3** [comment]
可能缺少相关驱动，是什么网卡？

**Comment by w675881684** [comment]
我用的网卡BCM5720遇到同样问题；kernel自带tg3.ko有点旧，需要额外下载编译
https://docs.broadcom.com/docs-and-downloads/docs/eula_download/570x/linux-3.137k.tar.gz

**Comment by jlijian3** [comment]
CentOS (2.6.32-358.el6.x86_64)
