### ISSUE TITLE
判断netmask 逻辑有问题

### ISSUE THREAD

**Issue by monkeyerKong** [jlijian3/lvs-snat#8]
系统:
[root@localhost ipvsadm]# uname -a
Linux localhost 2.6.32 #1 SMP Tue Jun 25 15:38:29 CST 2019 x86_64 x86_64 x86_64 GNU/Linux

加载模块信息：
[root@localhost ipvsadm]# lsmod |grep ip_v
ip_vs_snat_sched        4418  1 
ip_vs                 184970  3 ip_vs_snat_sched
ipv6                  324335  268 ip_vs,ip6t_REJECT,nf_conntrack_ipv6,nf_defrag_ipv6
[root@localhost ipvsadm]# 

添加一个snat规则如下：
ipvsadm -K -f 1 -F 10.241.3.0/16  --oif eth0 -U 114.112.34.28 -O random
命令正常执行
[root@localhost ipvsadm]# ipvsadm -ln -f 1
Prot LocalAddress:Port Scheduler Flags
  -> SourceAddr          DestAddr            GW               Oif             SnatIp                          Algo    NewGW            ActConn   InActConn 
FWM  1 snat_sched
  -> 10.241.3.0/16       0.0.0.0/0           0.0.0.0          eth0            114.112.34.28                   random  0.0.0.0          0         0         
[root@localhost ipvsadm]# 

message中报错：
Jun 25 17:49:13 localhost kernel: [ 7455.983028] IPVS: SNAT rule saddr 10.241.3.0 not match zmask 255.255.0.0

实际上10.241.3.0/16的netmask 就是255.255.0.0

**Comment by monkeyerKong** [comment]
ipvsadm -K -f 1 -F 10.241.0.0/16 --oif eth0 -U 114.112.34.28 -O random
能够正常。
对于cidr
10.241.1.0/16
10.241.2.0/16
这些都正确的

**Comment by jlijian3** [comment]
> ipvsadm -K -f 1 -F 10.241.0.0/16 --oif eth0 -U 114.112.34.28 -O random
> 能够正常。
> 对于cidr
> 10.241.1.0/16
> 10.241.2.0/16
> 这些都正确的

逻辑没错，严格匹配的网段
